name: LoginPoint
description: A Bukkit plugin that allows you to set a point, where players will be teleported after login.
main: pl.chormon.LoginPoint.LoginPoint
author: Chormon
version: 1.0.0
commands:
  setloginpoint:
    description: Set point where players will be teleport after login.
    usage: /<command> [<x> <y> <z> [<worldname>]]
    permission: <plugin name>.spawnpoint
    permission-message: You don't have <permission>
permissions:
  loginpoint.*:
    description: Gives access to all LoginPoint commands
    children:
      loginpoint.setloginpoint: true
loginpoint.setloginpoint:
  description: Allows you to set login point
  default: op